services:
  - type: web
    name: cajeros-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: ${cajeros-db.connectionString} # Usa la variable de entorno de Render